title: Jyoti Gupta
#logo: /assets/img/headshot_circle.png
description: Experienced Consulting Data Analyst skilled in transforming complex data into actionable insights. Proficient in client and stakeholder management.

show_downloads : true
theme: jekyll-theme-minimal
