title: Jyoti Gupta
#logo: /assets/img/headshot_circle.png
description: Alteryx and Tableau certified Data Consultant
Links: https://www.linkedin.com/in/jgupta306/
show_downloads : true
theme: jekyll-theme-minimal
